[versions]
accompanistPermissions = "0.37.3"
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
androidx-activityCompose = "1.11.0"
androidx-core-splashscreen = "1.0.1"
androidx-lifecycle = "2.9.5"
androidx-datastore = "1.1.7"
barcodeScanning = "17.3.0"
bignum = "0.3.10"
camera2 = "1.5.0"
compose-plugin = "1.9.0"
decompose = "3.4.0"
extJunit = "1.3.0"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
atto-commons = "5.4.0"
jna = "5.17.0"
junitJupiter = "5.13.4"
navigationCompose = "2.9.4"
koin = "4.1.1"
qrose = "1.0.1"
rules = "1.7.0"
transportRuntime = "4.0.0"
material3WindowSize = "0.5.0"
activityKtx = "1.11.0"
slf4j = "2.0.17"
roomCommon = "2.8.0"
ksp = "2.3.1"
sqlite = "2.6.0"
androidx-biometric = "1.2.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera2" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera2" }
androidx-ext-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "extJunit" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "rules" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
atto-commons-wallet = { module = "cash.atto:commons-wallet", version.ref = "atto-commons" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
# Koin dependencies
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
material3-window-size = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "material3WindowSize" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }
transport-runtime = { group = "com.google.android.datatransport", name = "transport-runtime", version.ref = "transportRuntime" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomCommon" }
room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomCommon" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCommon" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kspCompose = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "roomCommon" }