name: Pull Request

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  build-android:
    permissions:
      contents: read
    uses: ./.github/workflows/android-build.yaml

  deploy-web:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs:
      - build
      - build-android
    steps:
      - uses: actions/checkout@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - id: deploy-web
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATTO_APPLICATION_LIVE }}
          channelId: preview
